### ISSUE TITLE
User Account "Katie Jordan" does not exist 

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#10]
# Module: 01
#### Step: 04

Description of issue

The User account "Katie Jordan" does not exist in M365 Enterprise Blank tenant. Can the instructions be changed to use another user account?
![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/133017642/5be2ddda-6ef8-45b4-a96f-0ca11e0621bf)

**Comment by dahans-msft2** [comment]
Have updated all the names to use Allan Deyoung and will update in the next push.
