### ISSUE TITLE
Microsoft 365 Domestic Calling Plan not available

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#11]
# Module: 01
#### Step: 11

Description of issue

Microsoft 365 Domestic Calling Plan check box is not available in UI. 

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/133017642/2636a482-c6cb-4ab3-9bab-362282ac4b36)

**Comment by dahans-msft2** [comment]
The instructions in Task 3 needed to be rewritten for the new "Marketplace" experience in the admin center.  Did you add the trial licenses from the marketplace before assigning to Isaiah?

**Comment by dahans-msft2** [comment]
Nm, I see the discrepancy in the name of the license, will update and resolve in next push.
