### ISSUE TITLE
Instruction Continuity

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#12]
# Module: 01
#### Step: 01

Description of issue:

Instructions are never given to sign into the Microsoft 365 Admin Center. 

"You are still signed in to MS721-CLIENT01 as “Admin” and to the Microsoft 365 admin center as MOD Administrator."

**Comment by dahans-msft2** [comment]
Fixed with next push
