### ISSUE TITLE
Excel File Appears Blank

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#14]
#Lab: 02
#### Step: 04

Description of issue

My test results did not populate, files appear null. Notice blank excel in the background.

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/72228536/7a63cdf1-2233-424b-9bd3-3bff25e5a249)

**Comment by dahans-msft2** [comment]
Wasn't able to repro this issue in a new instance.  But I did add an instruction to "Allow" the test through the Windows Firewall.
