### ISSUE TITLE
Missing command output

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#15]
# Lab: 03
#### Step: 6-10

Description of issue
Output of this command is empty, I think this is because we populate all of these policies in labs 1 & 2?

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/72228536/d4b61d26-f4af-4279-a760-831f67c91bf4)

**Comment by dahans-msft2** [comment]
This is expected at this point, since we haven't setup anything yet for Direct Routing.
