### ISSUE TITLE
Missing Data ? 

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#16]
# Lab: 03
#### Step: 3

Description of issue
I didn't see any data present. Is this because this is populated during labs 1&2? 
![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/72228536/d78c5677-c834-418c-ad2c-c3c2979278f9)

**Comment by dahans-msft2** [comment]
Yes, all the Emergency addresses and locations are configured in Lab 2.
