### ISSUE TITLE
Missing Lab Number

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#20]
# Lab: 04
#### Step: 4-7

Description of issue
Throws errors, though we never ran a script to establish a 'lab number' in this environment (labs 1,2,4)

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/72228536/28e27d6a-1533-4034-9e7a-dcbbf5acb23c)

**Comment by dahans-msft2** [comment]
I updated the steps to just use the default lab domain (MS365x99256249) and it's not giving an error.  If the user had run through Lab 3, the domain would be present from running the script, but to avoid issues, we can just use the default lab domain. There's no reason for it to necessarily be on the custom lab domain.
