### ISSUE TITLE
Suggest Rewrite of Instructions

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#25]
# Lab: 04
#### Step:9

Description of issue

Navigation is a little off for Teams Health.

'While on the call, press the three dots in the top right of the Teams client and select call health.'

Should be 

'While on the call, press the three dots in the top right of the Teams client and select settings, select call health.'

**Comment by dahans-msft2** [comment]
Fixed in next push.
