### ISSUE TITLE
Missing Option

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#27]
# Lab: 04
#### Step:5-7

Description of issue
![Mod4_Shot3](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/72228536/6b95c804-5aca-4817-ba24-9e19eac83db8)

Option does not exist.

**Comment by dahans-msft2** [comment]
Updated to the PSTN usage report, will be fixed in next push.
