### ISSUE TITLE
Marketplace not visible in 365 admin center.

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#31]
# Lab: 1
#### Step: 2

We're told to go to "Marketplace" to get the licences, but this isn't showing the 365 Admin center in most tenants.  It's still Billing / Puchase services.

**Comment by dahans-msft2** [comment]
Resolved with PR #41, thanks @AnnetteGill!
