### ISSUE TITLE
Suggest using INI file to configure the SBC in Lab 3, Exercise 3

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#40]
# Lab: 03
### Tasks: 1-9 

This isn't an error but a suggestion.

In the Trainer Prep Guide, you say that if the student hasn't configured the SBC correctly after doing exercise 3, they can upload an INI file, which will do most of the configuration of the SBC.  Then they only have to configure IP groups and a classification rule.

Could I suggest that the students are told to do this anyway, rather than spending a long time configuring it all themselves (tasks 1 to 9)?  

The time estimated for Exercise 3 is 45 minutes, so these tasks are long and complicated and can easily go wrong.

It's unlikely that the students will use this exact type of SBC, and it's quite possible that it will be set up by experts or vendors, not the Teams admins, who are the people on this course.  So the students won't gain any useful knowledge or experience by doing all this work, which might not even make sense to them.

Could I suggest that Exercise 3, Tasks 1 to 9 are replaced with the steps in the Trainer Prep Guide? (attached)

This whole lab is long and complex, and making Exercise 3 much shorter would enable the students to concentrate on the more relevant material.
[MS-721T00A-ENU-TrainerPrepGuide.pdf](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/files/12769818/MS-721T00A-ENU-TrainerPrepGuide.pdf)

**Comment by dahans-msft2** [comment]
@AnnetteGill That's a good and fair suggestion, and one I'll take into consideration for the next major revision.  It would be a good idea for manageability reasons too, so we can control that INI file if something needs updating. This will help make room for time on other labs as well.  Thanks!

**Comment by AnnetteGill** [comment]
Many thanks for considering this, and for resolving all the other issues that I reported.
