### ISSUE TITLE
Why aren't error reports for MS-700 being dealt with?

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#44]
@dahans-msft2 I notice you have dealt promptly with error reports made here for this course.  But do you know why no-one is dealing with the error reports for the other Teams course, MS-700?

There are outstanding issues dating back to March, and the last issue that was resolved was in April.  

I've reported several errors over the last few months that are just being ignored.  Changes in the user interfaces mean that many lab instructions don't work any more, and the students are struggling to complete some of the lab exercises.  

Do you have contact with whoever is managing MS-700?  

If so, please could you ask them to deal with these outstanding issues?  The poor quality of the lab instructions is embarrassing and I keep having to apologise to students for it.

**Comment by dahans-msft2** [comment]
Hi @AnnetteGill, there've been some changes in ownership for that course in recent months, so I'll work with the new author to make sure the issues are addressed.  Thanks for your concern and feedback.

**Comment by AnnetteGill** [comment]
Thank you, that would be much appreciated .
