### ISSUE TITLE
Lab 4 - normalisation rules issue

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#54]
Lab: 4 
Exercise: 4 
Task: 2 
Step: 15  

This will fail as there are 2 existing normalization rules -  the new inserted rule will not be used until it is raised to be number 1 or 2 in priority.

Can these steps please be recreated.

**Comment by dahans-msft2** [comment]
Acknowledged, I'll take a look at this next week @LewisGoDeploy, thanks for bringing this to my attention.  Would you say it just needs a new step to raise the priority to 1 or 2?
