### ISSUE TITLE
Command doesn't work in lab 4

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#55]
#### Step: 5

Description of issue

Step 5 states to run the following command: Set-CsPhoneNumberAssignment -Identity NestorW@lab<LAB NUMBER>.o365ready.com -PhoneNumber "+14255551122" -PhoneNumberType DirectRouting

This command fails, because the user cannot be found. I've gone back through the lab and I can't find any step where you change Nestor's account to this domain. Is this a mistake from the author?

You are instructed to assign Megan Bowen the custom domain in Lab 3 task 6, does this need changing to Nestor?

**Comment by dahans-msft2** [comment]
@LewisGoDeploy Acknowledge, I'll take a look at this by the end of the week.  It may just be a name mixup.
